### ISSUE TITLE
Stabilization of Autosharding

### ISSUE THREAD

**Issue by hdost** [kubernetes/kube-state-metrics#1983]
**What would you like to be added**:

Autosharding stabilized and not considered experimental.

**Why is this needed**:

The experimental feature has been experimental for 5 years. It's not clear to me (and likely other users) what the actual status of this is. [Introduced](https://github.com/kubernetes/kube-state-metrics/commit/f3d41de450a1f72397ae935af3c2a58d7bb8afa4) in 1.8.0 now on 2.7.0 at time of writing this. Is it still experimental? What would prevent it from becoming stable? What should be done before it becomes stable?

**Describe the solution you'd like**

Nothing new necessarily, but mostly 

```[tasklist]
### Tasks
- [ ] Gather some sort of sentiment (understandably hard to do) of why the experimental feature might be hard to maintain. Or things that maybe should change before stabilized.
- [ ] Make changes to autosharding ?
- [ ] Remove feature or remove experimental notices.
- [ ] Update documentation.
```

**Additional context**

**Comment by mrueg** [comment]
@hdost likely it can be considered stable since there were no drastic changes (if at all) in the last releases to it. 
What would help promoting it to stable is user feedback like yours. Are you using it in production? Is it working as expected? Are there any outstanding issues?

**Comment by hdost** [comment]
> @hdost likely it can be considered stable since there were no drastic changes (if at all) in the last releases to it. 
> 
> What would help promoting it to stable is user feedback like yours. Are you using it in production? Is it working as expected? Are there any outstanding issues?

Currently we are not but we are considering it. However it was a point of hesitation to design some changes only to have the feature be removed. At least we can start to test it out. For sure some feedback to come as we test. 👍🏼

**Comment by dashpole** [comment]
@CatherineF-dev any updates on this issue?

**Comment by hdost** [comment]
Bump

**Comment by hdost** [comment]
Related ticket https://github.com/kubernetes/kube-state-metrics/issues/2688
