### ISSUE TITLE
v1.1.0 Release tracking issue

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kube-state-metrics#268]
- [x] Update `client-go` to v5.0.0 release. `client-go` v5.0.0 will support Kubernetes 1.8. With updating to v5.0.0 `client-go`, kube-state-metrics will support Kubernetes 1.8. But `client-go` 
 v5.0.0 has not been released. As discussed with @caesarxuchao offline, v5.0.0 `client-go` should be released in this week. If this is reliable, kube-state-metrics should wait for updating `client-go` but this should be confirmed by @caesarxuchao . #269 @andyxning
- [x] Update `kubernetes` to tag 1.8. #269 @andyxning 
- [ ] ~~add `kube_persistentvolume_status`.~~ #236  @zouyee
- [ ] ~~add ingress metric~~ #225 @zouyee  
- [ ] ~~add service type~~ #224  @zouyee 
- [ ] ~~add simple componentstatus metrics~~ #219 @zouyee 
- [x] add a compatibility description about different group version for resources. As discussed in #265. #271 @andyxning

As for `use protobuf instead of json`(#264) and `checkout kubernetes cluster supported feature`(#220) can not be fulfilled in this week, imo, i suggest to postpone those PRs to next release.

This release schedule heavily depends on @zouyee , could you please take some time to help us to make this.

@brancz @matthiasr

**Comment by zouyee** [comment]
👍

**Comment by brancz** [comment]
I think there are a ton of features that are already in master, so I would say we cut the release once we have client-go 5.0.

**Comment by andyxning** [comment]
After a offline discussion with @caesarxuchao , he can give us some ETA about when the client-go v5.0.0 will released.

**Comment by caesarxuchao** [comment]
The tip of the client-go release-5.0 branch is very close to kubernetes-v1.8.0, the only missing bug fix is https://github.com/kubernetes/kubernetes/pull/52946 and the [version information](https://github.com/kubernetes/kubernetes/commit/0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4). If client-go doesn't make v5.0.0 soon, you can track the latest commit of the release-5.0 branch.

**Comment by andyxning** [comment]
After a look at those two commits, it turns out that kube-state-metrics reference package `k8s.io/apimachinery/pkg/util/net` which is not cherrypicked to `kubernetes/apimachinery` release-1.8 branch.

**Comment by andyxning** [comment]
@caesarxuchao Seems like the unsynced  commits about `util/net` has only new function added and nothing changed. I think it is fine to use release-5.0 to update. 

@brancz I will give it a try.

**Comment by andyxning** [comment]
@brancz #269 has been updated and can be reviewed for now. PTAL.

**Comment by andyxning** [comment]
> I think there are a ton of features that are already in master, so I would say we cut the release once we have client-go 5.0.

@brancz I agree that we already have a lot of features and can release v1.1.0 for now. So i update the milestone for #224 #225 #236 #219 to v1.2.0.

**Comment by brancz** [comment]
sgtm :+1:

**Comment by andyxning** [comment]
But i am still want to add a description about:
> add a compatibility description about different group version for resources.

in readme. I will fire another PR to update readme later.

**Comment by andyxning** [comment]
Close this as we have released v1.1.0-rc.0.
